
--==============================================================
-- TABLES & PRIMARY KEYS
--==============================================================

-- Tabela: USUARIO
CREATE TABLE usuario (
                         id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         nome            VARCHAR2(50) NOT NULL,
                         email           VARCHAR2(50) NOT NULL,
                         senha           VARCHAR2(50) NOT NULL,
                         data_cadastro   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT pk_usuario PRIMARY KEY (id),
                         CONSTRAINT uq_usuario_email UNIQUE (email)
);

-- Tabela: CONTA
CREATE TABLE conta (
                       id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       agencia         INT NOT NULL,
                       numero          INT NOT NULL,
                       tipo_conta      VARCHAR2(50) NOT NULL,
                       saldo           NUMBER(13,2) DEFAULT 0.00 NOT NULL,
                       data_criacao    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       CONSTRAINT pk_conta PRIMARY KEY (id)
);

-- Tabela: CATEGORIA
CREATE TABLE categoria (
                           id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           nome_categoria  VARCHAR2(50) NOT NULL,
                           tipo_categoria  VARCHAR2(50) NOT NULL, -- Ex: 'Receita' ou 'Despesa'
                           CONSTRAINT pk_categoria PRIMARY KEY (id)
);

-- Tabela: META
CREATE TABLE meta (
                      id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      nome            VARCHAR2(50) NOT NULL,
                      data_criacao    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      valor_alvo      NUMBER(13,2) NOT NULL,
                      valor_atual     NUMBER(13,2) DEFAULT 0.00 NOT NULL,
                      status_meta     VARCHAR2(50) NOT NULL,
                      data_alvo       DATE NOT NULL,
                      fk_categoria_id INT,
                      CONSTRAINT pk_meta PRIMARY KEY (id)
);

-- Tabela: TRANSACAO
CREATE TABLE transacao (
                           id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           descricao       VARCHAR2(50) NOT NULL,
                           data_criacao    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           valor           NUMBER(13,2) NOT NULL,
                           tipo_transacao  VARCHAR2(50) NOT NULL, -- Ex: 'IN' ou 'OUT'
                           fk_conta_id     INT NOT NULL,
                           fk_categoria_id INT NOT NULL,
                           CONSTRAINT pk_transacao PRIMARY KEY (id)
);


--==============================================================
-- JUNCTION TABLES (Tabelas de Associação)
--==============================================================

-- Tabela: USUARIO_CONTA (Relacionamento N:N entre Usuario e Conta)
CREATE TABLE usuario_conta (
                               fk_usuario_id   INT NOT NULL,
                               fk_conta_id     INT NOT NULL,
                               CONSTRAINT pk_usuario_conta PRIMARY KEY (fk_usuario_id, fk_conta_id)
);

-- Tabela: USUARIO_META (Relacionamento N:N entre Usuario e Meta)
CREATE TABLE usuario_meta (
                              fk_usuario_id   INT NOT NULL,
                              fk_meta_id      INT NOT NULL,
                              CONSTRAINT pk_usuario_meta PRIMARY KEY (fk_usuario_id, fk_meta_id)
);

--==============================================================
-- FOREIGN KEYS
--==============================================================

-- Foreign Keys para USUARIO_CONTA
ALTER TABLE usuario_conta
    ADD CONSTRAINT fk_usuarioconta_usuario FOREIGN KEY (fk_usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE;

ALTER TABLE usuario_conta
    ADD CONSTRAINT fk_usuarioconta_conta FOREIGN KEY (fk_conta_id)
        REFERENCES conta (id) ON DELETE CASCADE;

-- Foreign Keys para USUARIO_META
ALTER TABLE usuario_meta
    ADD CONSTRAINT fk_usuariometa_usuario FOREIGN KEY (fk_usuario_id)
        REFERENCES usuario (id) ON DELETE CASCADE;

ALTER TABLE usuario_meta
    ADD CONSTRAINT fk_usuariometa_meta FOREIGN KEY (fk_meta_id)
        REFERENCES meta (id) ON DELETE CASCADE;

-- Foreign Keys para TRANSACAO
ALTER TABLE transacao
    ADD CONSTRAINT fk_transacao_conta FOREIGN KEY (fk_conta_id)
        REFERENCES conta (id) ON DELETE CASCADE;

ALTER TABLE transacao
    ADD CONSTRAINT fk_transacao_categoria FOREIGN KEY (fk_categoria_id)
        REFERENCES categoria (id) ON DELETE SET NULL;

-- Foreign Keys para META
ALTER TABLE meta
    ADD CONSTRAINT fk_meta_categoria FOREIGN KEY (fk_categoria_id)
        REFERENCES categoria (id) ON DELETE SET NULL;
